# Use a base image
FROM node:latest

# Set the working directory
WORKDIR /usr/src/app

# # Copy package.json and package-lock.json
# COPY package*.json ./
# Copy package.json and package-lock.json
COPY package*.json ./


# Install dependencies
RUN npm install

# Copy the source code to the working directory
COPY . .

# Expose the port your backend is running on
EXPOSE 5000

# Define the command to run your backend
# CMD node ./bin/www
CMD ["npm","start"]