name: Next.js CI

on:
  push:
    branches:
      - main

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set Working Directory
        run: |
          echo "Setting working directory..."
          cd ${{ github.workspace }}
          ls
          cd mail-delivery-time-prediction-system-front-end-part  
          ls 
      

      - name: Install Dependencies
        run: |
          echo "Running Installing Dependencies..."
          ls
          cd mail-delivery-time-prediction-system-front-end-part
          npm install
        

      - name: Run Linting
        run: |
           ls
           cd mail-delivery-time-prediction-system-front-end-part
           npm run lint
        env:
          CI: true















# name: Next.js CI

# on:
#   push:
#     branches:
#       - main

# jobs:
#   lintTest:
#     name: Lint
#     runs-on: ubuntu-latest
#     steps:
#       - name: Clone Repository
#         uses: actions/checkout@v2
      
#       - name: Install Dependencies
#         run: |
#           echo "Running Installing Dependencies..."
#           npm install

#       - name: Run Linting
#         run: |
#           echo "Running Linting Tests..."
#           npm run lint    
#         env:
#           CI: true
